export const IPC_INVOKE = {
  CONFIG_LOAD_PLAN: 'CONFIG/LOAD_PLAN',
  FLOW_SET_PHASE:   'FLOW/SET_PHASE',
  DRAW_REQUEST:     'DRAW/REQUEST',
  SPONSOR_START:    'SPONSOR/START',
  SPONSOR_STOP:     'SPONSOR/STOP',
  MINIGAME_RESULT:  'MINIGAME/RESULT',
  LAYOUT_BIND:      'LAYOUT/BIND_DISPLAY',
  THEME_SET:        'THEME/SET',
} as const;

// Main -> Renderer (events)
export const IPC_SEND = {
  STATE_PATCH:      'STATE/SESSION_PATCH',
  PHASE_CHANGED:    'FLOW/PHASE_CHANGED',
  DRAW_NEW_NUMBER:  'DRAW/NEW_NUMBER',
  SPONSOR_SHOW:     'SPONSOR/SHOW',
  LIGHTING_CUE:     'LIGHTING/CUE',
} as const;

export type Phase =
  | 'INTRO'
  | 'COUNTDOWN'
  | 'INSTRUCTIONS'
  | 'PRIZE_SPONSORS'
  | 'DRAW_LOOP'
  | 'WINNER'
  | 'MINIGAME';